### ISSUE TITLE
Post Content & Excerpt are not copy.

### ISSUE THREAD

**Issue by YChWork** [enricobattocchi/duplicate-post#1]
HI

I found an issue, where the post content & excerpt are not copy over when i duplicate the post. 
After debugged the code and notice that, this is because of the strict comparison issue.
`intval( get_option( 'duplicate_post_copycontent' ) ) === '1'  `
As you can see above code, since it's using a strict comparison it should be int instead of string. 
File : duplicate-post-admin.php
There are a few of the same issue related to that. 

Thank you.

**Comment by enricobattocchi** [comment]
Thanks! Still haven't found the time to test extensively the code after refactoring.
